<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(RunConfiguration)' == 'https' ">
    <ExternalConsole>true</ExternalConsole>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(RunConfiguration)' == 'http' ">
    <ExternalConsole>true</ExternalConsole>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="7.0.20" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="7.0.20" PrivateAssets="all" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="7.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.20">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MudBlazor" Version="7.5.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\EmrysSerenAPI\EmrysSerenAPI.csproj" />
    <ProjectReference Include="..\EmrysSerenShared\EmrysSerenShared.csproj" />
    <ProjectReference Include="..\EmrysSerenData\EmrysSerenData.csproj">
      <GlobalPropertiesToRemove></GlobalPropertiesToRemove>
    </ProjectReference>
  </ItemGroup>

</Project>
